### ISSUE TITLE
PHP Fatal error:  Class 'Controllers\SiteController' not found 

### ISSUE THREAD

**Issue by komputronika** [jeremejazz/fatfree-boilerplate#1]
Hello...

I have installed needed components with composer and bower.

But I got this error when first time to try:

      PHP Fatal error:  Class 'Controllers\SiteController' not found in /mnt/data/DATA/Web/f3- 
      boilerplate/app/controllers/welcome.php on line 3
      Fatal error: Class 'Controllers\SiteController' not found

Please give me suggestions.
Thanks

**Comment by jeremejazz** [comment]
Hello sorry I don't use PHP much these days. As for the error I think it has something to do with the case I used for the namespace. It should match the folder 
eg. Controllers should be controllers 

http://php.net/manual/en/function.spl-autoload-register.php

I have pushed a new commit that to fix this.
